/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/mem_ctrl.v:1.1-52.10" *)
module mem_ctrl(clk, rstn, psel, penable, pwrite, paddr, pwdata, prdata, pready, s_cs, s_we, s_addr, s_din, s_dout);
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  wire _00_;
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  wire _01_;
  (* src = "rtl/mem_ctrl.v:5.28-5.31" *)
  input clk;
  wire clk;
  (* src = "rtl/mem_ctrl.v:11.28-11.33" *)
  input [7:0] paddr;
  wire [7:0] paddr;
  (* src = "rtl/mem_ctrl.v:9.28-9.35" *)
  input penable;
  wire penable;
  (* src = "rtl/mem_ctrl.v:13.28-13.34" *)
  output [31:0] prdata;
  (* src = "rtl/mem_ctrl.v:14.28-14.34" *)
  output pready;
  (* src = "rtl/mem_ctrl.v:8.28-8.32" *)
  input psel;
  wire psel;
  (* src = "rtl/mem_ctrl.v:12.28-12.34" *)
  input [31:0] pwdata;
  wire [31:0] pwdata;
  (* src = "rtl/mem_ctrl.v:10.28-10.34" *)
  input pwrite;
  wire pwrite;
  (* src = "rtl/mem_ctrl.v:6.28-6.32" *)
  input rstn;
  wire rstn;
  (* src = "rtl/mem_ctrl.v:18.28-18.34" *)
  output [7:0] s_addr;
  (* src = "rtl/mem_ctrl.v:16.28-16.32" *)
  output s_cs;
  (* src = "rtl/mem_ctrl.v:19.28-19.33" *)
  output [31:0] s_din;
  (* src = "rtl/mem_ctrl.v:20.28-20.34" *)
  input [31:0] s_dout;
  wire [31:0] s_dout;
  (* src = "rtl/mem_ctrl.v:17.28-17.32" *)
  output s_we;
  AND2_X1 _02_ (
    .A1(psel),
    .A2(penable),
    .ZN(_00_)
  );
  AND3_X1 _03_ (
    .A1(psel),
    .A2(penable),
    .A3(pwrite),
    .ZN(_01_)
  );
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_addr[0] <= 1'h0;
    else if (_00_) s_addr[0] <= paddr[0];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_addr[1] <= 1'h0;
    else if (_00_) s_addr[1] <= paddr[1];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_addr[2] <= 1'h0;
    else if (_00_) s_addr[2] <= paddr[2];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_addr[3] <= 1'h0;
    else if (_00_) s_addr[3] <= paddr[3];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_addr[4] <= 1'h0;
    else if (_00_) s_addr[4] <= paddr[4];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_addr[5] <= 1'h0;
    else if (_00_) s_addr[5] <= paddr[5];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_addr[6] <= 1'h0;
    else if (_00_) s_addr[6] <= paddr[6];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_addr[7] <= 1'h0;
    else if (_00_) s_addr[7] <= paddr[7];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) pready <= 1'h0;
    else pready <= s_cs;
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_cs <= 1'h0;
    else s_cs <= _00_;
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_we <= 1'h0;
    else s_we <= _01_;
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[0] <= 1'h0;
    else if (s_cs) prdata[0] <= s_dout[0];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[1] <= 1'h0;
    else if (s_cs) prdata[1] <= s_dout[1];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[2] <= 1'h0;
    else if (s_cs) prdata[2] <= s_dout[2];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[3] <= 1'h0;
    else if (s_cs) prdata[3] <= s_dout[3];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[4] <= 1'h0;
    else if (s_cs) prdata[4] <= s_dout[4];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[5] <= 1'h0;
    else if (s_cs) prdata[5] <= s_dout[5];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[6] <= 1'h0;
    else if (s_cs) prdata[6] <= s_dout[6];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[7] <= 1'h0;
    else if (s_cs) prdata[7] <= s_dout[7];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[8] <= 1'h0;
    else if (s_cs) prdata[8] <= s_dout[8];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[9] <= 1'h0;
    else if (s_cs) prdata[9] <= s_dout[9];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[10] <= 1'h0;
    else if (s_cs) prdata[10] <= s_dout[10];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[11] <= 1'h0;
    else if (s_cs) prdata[11] <= s_dout[11];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[12] <= 1'h0;
    else if (s_cs) prdata[12] <= s_dout[12];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[13] <= 1'h0;
    else if (s_cs) prdata[13] <= s_dout[13];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[14] <= 1'h0;
    else if (s_cs) prdata[14] <= s_dout[14];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[15] <= 1'h0;
    else if (s_cs) prdata[15] <= s_dout[15];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[16] <= 1'h0;
    else if (s_cs) prdata[16] <= s_dout[16];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[17] <= 1'h0;
    else if (s_cs) prdata[17] <= s_dout[17];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[18] <= 1'h0;
    else if (s_cs) prdata[18] <= s_dout[18];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[19] <= 1'h0;
    else if (s_cs) prdata[19] <= s_dout[19];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[20] <= 1'h0;
    else if (s_cs) prdata[20] <= s_dout[20];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[21] <= 1'h0;
    else if (s_cs) prdata[21] <= s_dout[21];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[22] <= 1'h0;
    else if (s_cs) prdata[22] <= s_dout[22];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[23] <= 1'h0;
    else if (s_cs) prdata[23] <= s_dout[23];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[24] <= 1'h0;
    else if (s_cs) prdata[24] <= s_dout[24];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[25] <= 1'h0;
    else if (s_cs) prdata[25] <= s_dout[25];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[26] <= 1'h0;
    else if (s_cs) prdata[26] <= s_dout[26];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[27] <= 1'h0;
    else if (s_cs) prdata[27] <= s_dout[27];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[28] <= 1'h0;
    else if (s_cs) prdata[28] <= s_dout[28];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[29] <= 1'h0;
    else if (s_cs) prdata[29] <= s_dout[29];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[30] <= 1'h0;
    else if (s_cs) prdata[30] <= s_dout[30];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) prdata[31] <= 1'h0;
    else if (s_cs) prdata[31] <= s_dout[31];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[0] <= 1'h0;
    else if (_00_) s_din[0] <= pwdata[0];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[1] <= 1'h0;
    else if (_00_) s_din[1] <= pwdata[1];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[2] <= 1'h0;
    else if (_00_) s_din[2] <= pwdata[2];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[3] <= 1'h0;
    else if (_00_) s_din[3] <= pwdata[3];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[4] <= 1'h0;
    else if (_00_) s_din[4] <= pwdata[4];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[5] <= 1'h0;
    else if (_00_) s_din[5] <= pwdata[5];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[6] <= 1'h0;
    else if (_00_) s_din[6] <= pwdata[6];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[7] <= 1'h0;
    else if (_00_) s_din[7] <= pwdata[7];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[8] <= 1'h0;
    else if (_00_) s_din[8] <= pwdata[8];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[9] <= 1'h0;
    else if (_00_) s_din[9] <= pwdata[9];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[10] <= 1'h0;
    else if (_00_) s_din[10] <= pwdata[10];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[11] <= 1'h0;
    else if (_00_) s_din[11] <= pwdata[11];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[12] <= 1'h0;
    else if (_00_) s_din[12] <= pwdata[12];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[13] <= 1'h0;
    else if (_00_) s_din[13] <= pwdata[13];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[14] <= 1'h0;
    else if (_00_) s_din[14] <= pwdata[14];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[15] <= 1'h0;
    else if (_00_) s_din[15] <= pwdata[15];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[16] <= 1'h0;
    else if (_00_) s_din[16] <= pwdata[16];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[17] <= 1'h0;
    else if (_00_) s_din[17] <= pwdata[17];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[18] <= 1'h0;
    else if (_00_) s_din[18] <= pwdata[18];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[19] <= 1'h0;
    else if (_00_) s_din[19] <= pwdata[19];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[20] <= 1'h0;
    else if (_00_) s_din[20] <= pwdata[20];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[21] <= 1'h0;
    else if (_00_) s_din[21] <= pwdata[21];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[22] <= 1'h0;
    else if (_00_) s_din[22] <= pwdata[22];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[23] <= 1'h0;
    else if (_00_) s_din[23] <= pwdata[23];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[24] <= 1'h0;
    else if (_00_) s_din[24] <= pwdata[24];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[25] <= 1'h0;
    else if (_00_) s_din[25] <= pwdata[25];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[26] <= 1'h0;
    else if (_00_) s_din[26] <= pwdata[26];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[27] <= 1'h0;
    else if (_00_) s_din[27] <= pwdata[27];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[28] <= 1'h0;
    else if (_00_) s_din[28] <= pwdata[28];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[29] <= 1'h0;
    else if (_00_) s_din[29] <= pwdata[29];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[30] <= 1'h0;
    else if (_00_) s_din[30] <= pwdata[30];
  (* src = "rtl/mem_ctrl.v:25.3-51.6" *)
  always @(posedge clk or negedge rstn)
    if (!rstn) s_din[31] <= 1'h0;
    else if (_00_) s_din[31] <= pwdata[31];
endmodule
